#pragma config(Sensor, S1,     Touch,               sensorTouch)
#pragma config(Sensor, S4,     Sonar,               sensorSONAR)
#pragma config(Motor,  motorA,          RightTire,     tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          LeftTire,      tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Donovan Torgerson

int MonitorSonar; // Creating a variable to hold the MonitorSonar value (as an integer).
int MonitorTouch;
int Left;
int Right;

 void RightTurn() // Right turn code
 {
  motor[LeftTire] = 0;
  motor[RightTire] = 0;
  nMotorEncoder[LeftTire] = 0;
  nMotorEncoder[RightTire] = 0;
  motor[LeftTire] = 30;
  motor[RightTire] = 30;
  while(nMotorEncoder[RightTire] < 510);
  motor[LeftTire] = 0;
  motor[RightTire] = 0;
  nMotorEncoder[RightTire] = 0;
  nMotorEncoder[LeftTire] = 0;
  motor[LeftTire] = 30;
  motor[RightTire] = -30;
  while(nMotorEncoder[RightTire] > -475);
  motor[LeftTire] = 0;
  motor[RightTire] = 0;
  nMotorEncoder[LeftTire] = 0;
  nMotorEncoder[RightTire] = 0;
  motor[LeftTire] = 30;
  motor[RightTire] = 30;
  while(nMotorEncoder[RightTire] < 400);
  wait1Msec(2000);
 }

 void LeftTurn() // Left turn code
 {
  motor[LeftTire] = 0;
  motor[RightTire] = 0;
  nMotorEncoder[LeftTire] = 0;
  nMotorEncoder[RightTire] = 0;
  motor[LeftTire] = -30;
  motor[RightTire] = -30;
  while(nMotorEncoder[LeftTire] > -125);
  motor[LeftTire] = 0;
  motor[RightTire] = 0;
  nMotorEncoder[RightTire] = 0;
  nMotorEncoder[LeftTire] = 0;
  motor[LeftTire] = -30;
  motor[RightTire] = 30;
  while(nMotorEncoder[LeftTire] > -482);
  motor[LeftTire] = 0;
  motor[RightTire] = 0;
  wait1Msec(2000);
 }

 void AdjustLeft() // Left adjustment code
 {
  nMotorEncoder[RightTire] = 0;
  nMotorEncoder[LeftTire] = 0;
  while(nMotorEncoder[LeftTire] > -180)
  {
    motor[LeftTire] = -30;
    motor[RightTire] = 30;
  }
  motor[LeftTire] = 0;
  motor[RightTire] = 0;
  wait1Msec(2000);
  nMotorEncoder[RightTire] = 0;
  nMotorEncoder[LeftTire] = 0;
  motor[LeftTire] = 30;
  motor[RightTire] = 30;
  while(nMotorEncoder[LeftTire] < 140);
  motor[LeftTire] = 0;
  motor[RightTire] = 0;
  nMotorEncoder[RightTire] = 0;
  nMotorEncoder[LeftTire] = 0;
  while(nMotorEncoder[LeftTire] < 160)
  {
    motor[LeftTire] = 30;
    motor[RightTire] = -30;
  }
  motor[LeftTire] = 0;
  motor[RightTire] = 0;
  wait1Msec(2000);
 }

 void AdjustRight() // Right adjustment code
 {
  nMotorEncoder[RightTire] = 0;
  nMotorEncoder[LeftTire] = 0;
  while(nMotorEncoder[RightTire] > -180)
  {
    motor[LeftTire] = 30;
    motor[RightTire] = -30;
  }
  motor[LeftTire] = 0;
  motor[RightTire] = 0;
  wait1Msec(2000);
  nMotorEncoder[RightTire] = 0;
  nMotorEncoder[LeftTire] = 0;
  motor[LeftTire] = 30;
  motor[RightTire] = 30;
  while(nMotorEncoder[RightTire] < 140);
  motor[LeftTire] = 0;
  motor[RightTire] = 0;
  nMotorEncoder[RightTire] = 0;
  nMotorEncoder[LeftTire] = 0;
  while(nMotorEncoder[RightTire] < 180)
  {
    motor[LeftTire] = -30;
    motor[RightTire] = 30;
  }
  motor[LeftTire] = 0;
  motor[RightTire] = 0;
  wait1Msec(2000);
 }

task WriteSonar()
{
	while (true)
	{
    MonitorSonar = SensorValue[Sonar]; // Assigning current sonar value to MonitorSonar integer.
    Left = nMotorEncoder[LeftTire];
    Right = nMotorEncoder[RightTire];
    nxtDisplayClearTextLine(3);
		nxtDisplayClearTextLine(4);
		nxtDisplayClearTextLine(5);
		nxtDisplayTextLine(3,"Eyes: :%d",MonitorSonar);
		nxtDisplayTextLine(4,"Left: :%d",Left);
		nxtDisplayTextLine(5,"Right: :%d",Right);
		wait1Msec(100);
  }

}

task WriteTouch()
{
  while (true)
  {
    MonitorTouch = SensorValue[Touch]; // Assigning current touch sensor value to MonitorTouch integer.
    nxtDisplayClearTextLine(6);
    nxtDisplayTextLine(6,"Touch: %d",MonitorTouch);
    wait1Msec(100);
  }
}

task main()
{
  MonitorSonar = 255;
  StartTask(WriteSonar);
  StartTask(WriteTouch);
  wait1Msec(500);
  motor[RightTire] = 30;
  motor[LeftTire] = 30;
//  LeftTurn();
  while(true)
  {
    if (MonitorTouch == 1)
    {
      LeftTurn();
    }
    else
    {
	    if (MonitorSonar > 23) // If sensor reading is greater than 23.
	    {
	      if (MonitorSonar > 27) // If sensor reading is greater than 27, run TurnRight.
	      {
	        RightTurn();
	      }
	      else // If sensor reading is between 23 and 33, run AdjustRight.
	      {
	        AdjustRight();
	      }
	    }
	    else if (MonitorSonar < 16) // If sensor reading is to close, run AdjustLeft.
	    {
	      AdjustLeft();

	    }
	    else // If sensor reading is between 16 and 23, drive straight.
	    {
	      motor[RightTire] = 30;
	      motor[LeftTire] = 30;
	    }
	  }
  }
 }
